### ISSUE TITLE
Not working with newest Sonos firmware 9.1

### ISSUE THREAD

**Issue by harobert1** [bencevans/sonos-cli#6]
After upgrading Sonos to v9.1 (build 45156150) sonos-cli does not work anymore. :-(

**Comment by bencevans** [comment]
This is due to https://github.com/bencevans/node-sonos/issues/332 as soon as it's fixed upstream we can get the updates into sonos-cli :)

**Comment by bencevans** [comment]
Yup!

**Comment by bencevans** [comment]
https://github.com/bencevans/sonos-cli/pull/7

**Comment by bencevans** [comment]
Pushed up some work to https://github.com/bencevans/sonos-cli/pull/7 testing with your systems would be appreciated

**Comment by bencevans** [comment]
Should be fixed by `v0.4.0`. Upgrade and give it a whirl! `npm install --global sonos-cli` :tada:

**Comment by harobert1** [comment]
I reinstalled everything on Linux Mint 18.3:
    curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
    sudo apt-get install -y nodejs
    sudo npm install --global sonos-cli

sonos-cli v0.5.0 was installed.

"sonos list-zones" gave this result:
    undefined
    undefined
    undefined

sonos-cli list-devices gave this:

    (node:11248) UnhandledPromiseRejectionWarning: TypeError: groups.forEach is not a function
    at initDevice.getAllGroups.then.groups (/usr/lib/node_modules/sonos-cli/cmds/listDevices.js:3:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    (node:11248) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated  either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
    (node:11248) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future,  promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

What should I do?

**Comment by svrooij** [comment]
Could you start the command with the debug parameter and post the output here?

`DEBUG=sonos* sonos list-zones`

**Comment by harobert1** [comment]
here is the output:
  sonos:main Sonos.GetAllGroups() +0ms
  sonos:service Service._request("GetZoneGroupState" {}) +0ms
  sonos:helpers Helpers.ParseXml "<s:Envelope xmlns:s=\"http://schemas.xmlsoap.org/soap/envelope/\" s:encodingStyle=\"http://schemas.xmlsoap.org/soap/encoding/\"><s:Body><u:GetZoneGroupStateResponse xmlns:u=\"urn:schemas-upnp-org:service:ZoneGroupTopology:1\"><ZoneGroupState>&lt;ZoneGroups&gt;&lt;ZoneGroup Coordinator=&quot;RINCON_949F3E064E9401400&quot; ID=&quot;RINCON_949F3E064E9401400:3169087958&quot;&gt;&lt;ZoneGroupMember UUID=&quot;RINCON_949F3E064E9801400&quot; Location=&quot;http://192.168.0.26:1400/xml/device_description.xml&quot; ZoneName=&quot;Nappali&quot; Icon=&quot;x-rincon-roomicon:living&quot; Configuration=&quot;1&quot; Invisible=&quot;1&quot; SoftwareVersion=&quot;45.1-56150&quot; MinCompatibleVersion=&quot;44.0-00000&quot; LegacyCompatibleVersion=&quot;36.0-00000&quot; ChannelMapSet=&quot;RINCON_7828CA230EF001400:LF,LF;RINCON_949F3E064E9801400:RF,RF&quot; BootSeq=&quot;57&quot; TVConfigurationError=&quot;0&quot; HdmiCecAvailable=&quot;0&quot; WirelessMode=&quot;0&quot; WirelessLeafOnly=&quot;0&quot; HasConfiguredSSID=&quot;1&quot; ChannelFreq=&quot;2462&quot; BehindWifiExtender=&quot;0&quot; WifiEnabled=&quot;1&quot; Orientation=&quot;0&quot; RoomCalibrationState=&quot;5&quot; SecureRegState=&quot;3&quot; VoiceState=&quot;0&quot; AirPlayEnabled=&quot;0&quot;/&gt;&lt;ZoneGroupMember UUID=&quot;RINCON_7828CA230EF001400&quot; Location=&quot;http://192.168.0.18:1400/xml/device_description.xml&quot; ZoneName=&quot;Nappali&quot; Icon=&quot;x-rincon-roomicon:living&quot; Configuration=&quot;1&quot; SoftwareVersion=&quot;45.1-56150&quot; MinCompatibleVersion=&quot;44.0-00000&quot; LegacyCompatibleVersion=&quot;36.0-00000&quot; ChannelMapSet=&quot;RINCON_7828CA230EF001400:LF,LF;RINCON_949F3E064E9801400:RF,RF&quot; BootSeq=&quot;51&quot; TVConfigurationError=&quot;0&quot; HdmiCecAvailable=&quot;0&quot; WirelessMode=&quot;0&quot; WirelessLeafOnly=&quot;0&quot; HasConfiguredSSID=&quot;1&quot; ChannelFreq=&quot;2462&quot; BehindWifiExtender=&quot;0&quot; WifiEnabled=&quot;1&quot; Orientation=&quot;0&quot; RoomCalibrationState=&quot;4&quot; SecureRegState=&quot;3&quot; VoiceState=&quot;0&quot; AirPlayEnabled=&quot;0&quot;/&gt;&lt;ZoneGroupMember UUID=&quot;RINCON_949F3E064B3C01400&quot; Location=&quot;http://192.168.0.25:1400/xml/device_description.xml&quot; ZoneName=&quot;Háló&quot; Icon=&quot;x-rincon-roomicon:living&quot; Configuration=&quot;1&quot; SoftwareVersion=&quot;45.1-56150&quot; MinCompatibleVersion=&quot;44.0-00000&quot; LegacyCompatibleVersion=&quot;36.0-00000&quot; BootSeq=&quot;29&quot; TVConfigurationError=&quot;0&quot; HdmiCecAvailable=&quot;0&quot; WirelessMode=&quot;0&quot; WirelessLeafOnly=&quot;0&quot; HasConfiguredSSID=&quot;1&quot; ChannelFreq=&quot;2462&quot; BehindWifiExtender=&quot;0&quot; WifiEnabled=&quot;1&quot; Orientation=&quot;0&quot; RoomCalibrationState=&quot;4&quot; SecureRegState=&quot;3&quot; VoiceState=&quot;0&quot; AirPlayEnabled=&quot;0&quot;/&gt;&lt;ZoneGroupMember UUID=&quot;RINCON_949F3E064E9401400&quot; Location=&quot;http://192.168.0.24:1400/xml/device_description.xml&quot; ZoneName=&quot;Dolgozó&quot; Icon=&quot;x-rincon-roomicon:living&quot; Configuration=&quot;1&quot; SoftwareVersion=&quot;45.1-56150&quot; MinCompatibleVersion=&quot;44.0-00000&quot; LegacyCompatibleVersion=&quot;36.0-00000&quot; BootSeq=&quot;27&quot; TVConfigurationError=&quot;0&quot; HdmiCecAvailable=&quot;0&quot; WirelessMode=&quot;0&quot; WirelessLeafOnly=&quot;0&quot; HasConfiguredSSID=&quot;1&quot; ChannelFreq=&quot;2462&quot; BehindWifiExtender=&quot;0&quot; WifiEnabled=&quot;1&quot; Orientation=&quot;0&quot; RoomCalibrationState=&quot;4&quot; SecureRegState=&quot;3&quot; VoiceState=&quot;0&quot; AirPlayEnabled=&quot;0&quot;/&gt;&lt;/ZoneGroup&gt;&lt;/ZoneGroups&gt;</ZoneGroupState></u:GetZoneGroupStateResponse></s:Body></s:Envelope>" +0ms
  sonos:service Parsed service response as JSON
  sonos:service {
  "s:Envelope": {
    "xmlns:s": "http://schemas.xmlsoap.org/soap/envelope/",
    "s:encodingStyle": "http://schemas.xmlsoap.org/soap/encoding/",
    "s:Body": {
      "u:GetZoneGroupStateResponse": {
        "xmlns:u": "urn:schemas-upnp-org:service:ZoneGroupTopology:1",
        "ZoneGroupState": "<ZoneGroups><ZoneGroup Coordinator=\"RINCON_949F3E064E9401400\" ID=\"RINCON_949F3E064E9401400:3169087958\"><ZoneGroupMember UUID=\"RINCON_949F3E064E9801400\" Location=\"http://192.168.0.26:1400/xml/device_description.xml\" ZoneName=\"Nappali\" Icon=\"x-rincon-roomicon:living\" Configuration=\"1\" Invisible=\"1\" SoftwareVersion=\"45.1-56150\" MinCompatibleVersion=\"44.0-00000\" LegacyCompatibleVersion=\"36.0-00000\" ChannelMapSet=\"RINCON_7828CA230EF001400:LF,LF;RINCON_949F3E064E9801400:RF,RF\" BootSeq=\"57\" TVConfigurationError=\"0\" HdmiCecAvailable=\"0\" WirelessMode=\"0\" WirelessLeafOnly=\"0\" HasConfiguredSSID=\"1\" ChannelFreq=\"2462\" BehindWifiExtender=\"0\" WifiEnabled=\"1\" Orientation=\"0\" RoomCalibrationState=\"5\" SecureRegState=\"3\" VoiceState=\"0\" AirPlayEnabled=\"0\"/><ZoneGroupMember UUID=\"RINCON_7828CA230EF001400\" Location=\"http://192.168.0.18:1400/xml/device_description.xml\" ZoneName=\"Nappali\" Icon=\"x-rincon-roomicon:living\" Configuration=\"1\" SoftwareVersion=\"45.1-56150\" MinCompatibleVersion=\"44.0-00000\" LegacyCompatibleVersion=\"36.0-00000\" ChannelMapSet=\"RINCON_7828CA230EF001400:LF,LF;RINCON_949F3E064E9801400:RF,RF\" BootSeq=\"51\" TVConfigurationError=\"0\" HdmiCecAvailable=\"0\" WirelessMode=\"0\" WirelessLeafOnly=\"0\" HasConfiguredSSID=\"1\" ChannelFreq=\"2462\" BehindWifiExtender=\"0\" WifiEnabled=\"1\" Orientation=\"0\" RoomCalibrationState=\"4\" SecureRegState=\"3\" VoiceState=\"0\" AirPlayEnabled=\"0\"/><ZoneGroupMember UUID=\"RINCON_949F3E064B3C01400\" Location=\"http://192.168.0.25:1400/xml/device_description.xml\" ZoneName=\"Háló\" Icon=\"x-rincon-roomicon:living\" Configuration=\"1\" SoftwareVersion=\"45.1-56150\" MinCompatibleVersion=\"44.0-00000\" LegacyCompatibleVersion=\"36.0-00000\" BootSeq=\"29\" TVConfigurationError=\"0\" HdmiCecAvailable=\"0\" WirelessMode=\"0\" WirelessLeafOnly=\"0\" HasConfiguredSSID=\"1\" ChannelFreq=\"2462\" BehindWifiExtender=\"0\" WifiEnabled=\"1\" Orientation=\"0\" RoomCalibrationState=\"4\" SecureRegState=\"3\" VoiceState=\"0\" AirPlayEnabled=\"0\"/><ZoneGroupMember UUID=\"RINCON_949F3E064E9401400\" Location=\"http://192.168.0.24:1400/xml/device_description.xml\" ZoneName=\"Dolgozó\" Icon=\"x-rincon-roomicon:living\" Configuration=\"1\" SoftwareVersion=\"45.1-56150\" MinCompatibleVersion=\"44.0-00000\" LegacyCompatibleVersion=\"36.0-00000\" BootSeq=\"27\" TVConfigurationError=\"0\" HdmiCecAvailable=\"0\" WirelessMode=\"0\" WirelessLeafOnly=\"0\" HasConfiguredSSID=\"1\" ChannelFreq=\"2462\" BehindWifiExtender=\"0\" WifiEnabled=\"1\" Orientation=\"0\" RoomCalibrationState=\"4\" SecureRegState=\"3\" VoiceState=\"0\" AirPlayEnabled=\"0\"/></ZoneGroup></ZoneGroups>"
      }
    }
  }
} +20ms
  sonos:helpers Helpers.ParseXml "<ZoneGroups><ZoneGroup Coordinator=\"RINCON_949F3E064E9401400\" ID=\"RINCON_949F3E064E9401400:3169087958\"><ZoneGroupMember UUID=\"RINCON_949F3E064E9801400\" Location=\"http://192.168.0.26:1400/xml/device_description.xml\" ZoneName=\"Nappali\" Icon=\"x-rincon-roomicon:living\" Configuration=\"1\" Invisible=\"1\" SoftwareVersion=\"45.1-56150\" MinCompatibleVersion=\"44.0-00000\" LegacyCompatibleVersion=\"36.0-00000\" ChannelMapSet=\"RINCON_7828CA230EF001400:LF,LF;RINCON_949F3E064E9801400:RF,RF\" BootSeq=\"57\" TVConfigurationError=\"0\" HdmiCecAvailable=\"0\" WirelessMode=\"0\" WirelessLeafOnly=\"0\" HasConfiguredSSID=\"1\" ChannelFreq=\"2462\" BehindWifiExtender=\"0\" WifiEnabled=\"1\" Orientation=\"0\" RoomCalibrationState=\"5\" SecureRegState=\"3\" VoiceState=\"0\" AirPlayEnabled=\"0\"/><ZoneGroupMember UUID=\"RINCON_7828CA230EF001400\" Location=\"http://192.168.0.18:1400/xml/device_description.xml\" ZoneName=\"Nappali\" Icon=\"x-rincon-roomicon:living\" Configuration=\"1\" SoftwareVersion=\"45.1-56150\" MinCompatibleVersion=\"44.0-00000\" LegacyCompatibleVersion=\"36.0-00000\" ChannelMapSet=\"RINCON_7828CA230EF001400:LF,LF;RINCON_949F3E064E9801400:RF,RF\" BootSeq=\"51\" TVConfigurationError=\"0\" HdmiCecAvailable=\"0\" WirelessMode=\"0\" WirelessLeafOnly=\"0\" HasConfiguredSSID=\"1\" ChannelFreq=\"2462\" BehindWifiExtender=\"0\" WifiEnabled=\"1\" Orientation=\"0\" RoomCalibrationState=\"4\" SecureRegState=\"3\" VoiceState=\"0\" AirPlayEnabled=\"0\"/><ZoneGroupMember UUID=\"RINCON_949F3E064B3C01400\" Location=\"http://192.168.0.25:1400/xml/device_description.xml\" ZoneName=\"Háló\" Icon=\"x-rincon-roomicon:living\" Configuration=\"1\" SoftwareVersion=\"45.1-56150\" MinCompatibleVersion=\"44.0-00000\" LegacyCompatibleVersion=\"36.0-00000\" BootSeq=\"29\" TVConfigurationError=\"0\" HdmiCecAvailable=\"0\" WirelessMode=\"0\" WirelessLeafOnly=\"0\" HasConfiguredSSID=\"1\" ChannelFreq=\"2462\" BehindWifiExtender=\"0\" WifiEnabled=\"1\" Orientation=\"0\" RoomCalibrationState=\"4\" SecureRegState=\"3\" VoiceState=\"0\" AirPlayEnabled=\"0\"/><ZoneGroupMember UUID=\"RINCON_949F3E064E9401400\" Location=\"http://192.168.0.24:1400/xml/device_description.xml\" ZoneName=\"Dolgozó\" Icon=\"x-rincon-roomicon:living\" Configuration=\"1\" SoftwareVersion=\"45.1-56150\" MinCompatibleVersion=\"44.0-00000\" LegacyCompatibleVersion=\"36.0-00000\" BootSeq=\"27\" TVConfigurationError=\"0\" HdmiCecAvailable=\"0\" WirelessMode=\"0\" WirelessLeafOnly=\"0\" HasConfiguredSSID=\"1\" ChannelFreq=\"2462\" BehindWifiExtender=\"0\" WifiEnabled=\"1\" Orientation=\"0\" RoomCalibrationState=\"4\" SecureRegState=\"3\" VoiceState=\"0\" AirPlayEnabled=\"0\"/></ZoneGroup></ZoneGroups>" +6ms
undefined
undefined
undefined

**Comment by TefaTBob** [comment]
I'm getting the same error, this is my bug report from DEBUG=sonos* sonos list-zones:

sonos:main Sonos.GetAllGroups() +0ms
  sonos:service Service._request("GetZoneGroupState" {}) +0ms
(node:77005) UnhandledPromiseRejectionWarning: StatusCodeError: 500 - "<s:Envelope xmlns:s=\"http://schemas.xmlsoap.org/soap/envelope/\" s:encodingStyle=\"http://schemas.xmlsoap.org/soap/encoding/\"><s:Body><s:Fault><faultcode>s:Client</faultcode><faultstring>UPnPError</faultstring><detail><UPnPError xmlns=\"urn:schemas-upnp-org:control-1-0\"><errorCode>501</errorCode></UPnPError></detail></s:Fault></s:Body></s:Envelope>"
    at new StatusCodeError (/usr/local/lib/node_modules/sonos-cli/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/usr/local/lib/node_modules/sonos-cli/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/sonos-cli/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/usr/local/lib/node_modules/sonos-cli/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/sonos-cli/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/sonos-cli/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
(node:77005) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:77005) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
